# Generated by Django 6.0.5 on 2026-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_albumphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Album publié"),
        ),
        migrations.AlterField(
            model_name="video",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Vidéo publiée"),
        ),
    ]
