# Generated by Django 6.0.5 on 2026-06-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_publicationreaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationreaction",
            name="reaction",
            field=models.CharField(
                choices=[
                    ("like", "J’aime"),
                    ("love", "J’adore"),
                    ("haha", "Haha"),
                    ("wow", "Wow"),
                    ("sad", "Triste"),
                    ("angry", "En colère"),
                ],
                default="like",
                max_length=16,
            ),
        ),
    ]
