# Generated by Django 6.0.5 on 2026-06-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_publicationreaction_reaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicationreaction",
            name="reaction",
        ),
        migrations.AddField(
            model_name="publicationreaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("love", "Love"),
                    ("wow", "Wow"),
                    ("sad", "Sad"),
                    ("angry", "Angry"),
                ],
                default="like",
                max_length=10,
            ),
        ),
    ]
