# Generated by Django 6.0.5 on 2026-06-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_remove_publicationreaction_reaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicationreaction",
            name="visitor_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
